version: 0.2

runtime-versions:

phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - npm install
      - npm run test
      - npm run sls -- deploy -s $STAGE -r $REGION
      - npm run acceptance